### ISSUE TITLE
Abstract some code from your scripts to functions in a separate file + write tests

### ISSUE THREAD

**Issue by dd5124** [UBC-MDS/DSCI522-2425-25-heart_disease_predictor#63]
Create at least 3-4 functions from your scripts. One per group member is the minimum.

**Comment by dd5124** [comment]
Create at least 3-4 functions from your scripts. One per group member is the minimum

**Comment by BChangs99** [comment]
Finished with these PRs:
https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/84
https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/83
