### ISSUE TITLE
Address feedback to improve the project

### ISSUE THREAD

**Issue by dd5124** [UBC-MDS/DSCI522-2425-25-heart_disease_predictor#64]
### [Peer Review](https://github.com/UBC-MDS/data-analysis-review-2024/issues/12#issuecomment-2537520503)

---

### **Organization**
- [x] #72
- [x] #71
- [x] [Organize files in the `report` folder into subfolders for better structure.](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/commit/704fb0f46221944bcf70efff16d43fae6b21e9d5)

---

### **Report**
- [x] [Ensure EDA is conducted exclusively on the training dataset to prevent data leakage.](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/79/commits/53de6cb46fa01639ee9fe745a43c6669ea679050)
  - [LINK](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/79/commits/15cf4c5586995dd7154f4ee238a08d10b5813d93)
- [x] [Expand the "Methods & Results" section with more explanatory notes and keep the "Discussion" focused on providing additional details. Discuss the motivation behind your scoring metrics in the context of "Heart Disease Prediction".](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/89)
- [x] [Provide more detail in the "Methods" section on how the dataset was split for training and testing (e.g., 70-30 split or cross-validation).](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/89)
- [x] #73
- [x] [References: Please ensure all softwares used in generating the analysis and report are properly attributed.](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/89)

---

### **Documentation**
- [x] [Pin `requests` version to `==2.24.0` instead of `>=2.24.0`.](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/commit/92e9e74bc2b7b78f7fcb1cf1958d242d9187b836)
- [x] #75
- [x] #74
  ```bash
  quarto render heart_disease_predictor_report.qmd --to html
  quarto render heart_disease_predictor_report.qmd --to pdf
  ```

---

### **Code**
- [x] #76
- [x] [Implement more specific exceptions (e.g., `InvalidColumnTypeError`, `MissingValueError`) instead of generic ones like `ValueError`.](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/commit/d1e3849dfffb0aa2e32b599f7ac7f58c42afb12d)
- [x] Move helper functions into separate modules for better organization.
  - [LINK1](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/commit/fc240272756a1cde597eacd3924520ff1713c34f), [LINK2](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/commit/be9ba5c8b969124a002e793d4f22840f44945650)
- [x] Modularize functions to improve code clarity and reusability & Abstract code from the `main()` function into separate functions to improve structure and readability.
  - [LINK1](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/66), [LINK2](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/79), [LINK3](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/84), [LINK4](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/83)
- [x] Unit Testing: Adding unit tests for each validation function would ensure the correctness of the logic when applied to different datasets. It can help catch edge cases and confirm that each function works as expected.
  - [LINK1](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/66), [LINK2](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/79), [LINK3](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/84), [LINK4](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/pull/83)
- [x] #88 [Line 38 Note 3:](https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/blob/main/README.md?plain=1)
---

### **Warnings**
- [x] #85

---

**Comment by BChangs99** [comment]
Related Issues: https://github.com/UBC-MDS/DSCI522-2425-25-heart_disease_predictor/issues/35
